---
format:
  html:
    toc: true
    css: justify.css
---

# Diseño de Encuesta.

## Diseño de cuestionario

El instrumento de recolección de información consiste en un cuestionario estructurado (tipo encuesta) dirigido a los principales actores de las escuelas: docentes, apoderados y estudiantes.

Este cuestionario fue diseñado para analizar la influencia de aspectos clave del mercado educativo en las percepciones y creencias sobre la meritocracia, así como su impacto en la formación ciudadana dentro de las escuelas, con un enfoque en su evolución a lo largo del tiempo. Los principales temas de interés analítico se organizan en los siguientes módulos:

- Módulo I: Meritocracia
- Módulo II: Preferencias y Desigualdad
- Módulo III: Ciudadanía
- Módulo IV: Datos Sociodemográficos

El cuestionario aplicado a estudiantes incluye un módulo experimental, en el que se entrega una condición de tratamiento y una condición de control. Al cuestionario aplicado a profesores se le agregan los módulos "Estructura de objetivos de rendimiento y dominio" y "Prácticas pedagógicas".

## Cuotas y tamaño de la muestra {#sec-quotas}

## Alcance del control de cuotas

## Restricción de factibilidad conocida (educación básica)

## Diseño longitudinal {#sec-longitudinal}

## Ponderación y calibración {#sec-weighting}

## Precisión, incertidumbre y errores ajenos al muestreo {#sec-errors}