project:
  type: book
  output-dir: docs

book:
  title: "Manual Metodológico de Encuesta EDUMER"
  reader-mode: true
  page-footer:
    left: |
      Meritocracia en la escuela (EDUMER): Fundamentos morales del mercado educativo y sus implicancias para la formación ciudadana en Chile
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  repo-url: https://jus-mer.com/
  repo-branch: main
  chapters:
    - index.qmd
    - 01-antecedentes.qmd
    - 02-diseno-encuesta.qmd
    - 03-cuestionario.qmd
    - 04-diseno-experimento.qmd
    - 05-diseno-items.qmd
    - 06-implementacion-encuesta.qmd
    - 07-base-datos.qmd
    - 08-etica.qmd
    - 09-libro-codigos.qmd
    - 10-apendice.qmd
    - 11-notas-tecnicas.qmd

  search:
    location: sidebar
    type: textbox
  sidebar:
    search: true
    style: docked
    pinned: false

format:
  html:
    theme:
      - cosmo
      - jusmer.scss
    css: justify.css
    code-link: true

editor: visual
lang: es

bibliography: "../input/bib/manual-metod.bib"
csl: "../input/bib/apa6.csl"

