project:
  type: book
  output-dir: .

book:
  title: "Manual Metodológico de Encuesta EDUMER"
  reader-mode: true
  page-footer:
    left: |
      Meritocracia en la escuela (EDUMER): Fundamentos morales del mercado educativo y sus implicancias para la formación ciudadana en Chile

    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  repo-url: https://jus-mer.com/
  repo-branch: main
  chapters:
    - edumer-book/index.qmd
    - edumer-book/01-diseno.qmd
    - edumer-book/02-instrumento.qmd
    - edumer-book/03-implementacion.qmd
    - edumer-book/04-bases-datos.qmd
    - edumer-book/05-libro-codigos.qmd
    - edumer-book/06-anexo-items.qmd
  search:
    location: sidebar
    type: textbox
  sidebar:
    search: true
    style: docked
    pinned: false


format:
  html:
    theme:
      - cosmo
      - edumer-book/jusmer.scss
    css: edumer-book/justify.css
    code-link: true
    number-sections: false

editor: visual
lang: es

bibliography: "edumer-book/bib/manual-metod.bib"
csl: "edumer-book/bib/apa6.csl"


